class GameQuestion {
  final String question;
  final String answer;
  final String hint;
  final String solution;
  GameQuestion(this.question, this.answer, this.hint, this.solution);
}

List<GameQuestion> gameQuestion = [
  GameQuestion("images/questions/lv1.svg", "24",
      "images/questions/hint_lv1.svg", "images/questions/solution_lv1.svg"),
  GameQuestion("images/questions/lv2.svg", "20",
      "images/questions/hint_lv2.svg", "images/questions/solution_lv2.svg"),
  GameQuestion("images/questions/lv3.svg", "8", "images/questions/hint_lv3.svg",
      "images/questions/solution_lv3.svg"),
  GameQuestion("images/questions/lv4.svg", "4", "images/questions/hint_lv4.svg",
      "images/questions/solution_lv4.svg"),
  GameQuestion("images/questions/lv5.svg", "16",
      "images/questions/hint_lv5.svg", "images/questions/solution_lv5.svg"),
  GameQuestion("images/questions/lv6.svg", "25",
      "images/questions/hint_lv6.svg", "images/questions/solution_lv6.svg"),
  GameQuestion("images/questions/lv7.svg", "14",
      "images/questions/hint_lv7.svg", "images/questions/solution_lv7.svg"),
  GameQuestion("images/questions/lv8.svg", "5", "images/questions/hint_lv8.svg",
      "images/questions/solution_lv8.svg"),
  GameQuestion("images/questions/lv9.svg", "52",
      "images/questions/hint_lv9.svg", "images/questions/solution_lv9.svg"),
  GameQuestion("images/questions/lv10.svg", "4",
      "images/questions/hint_lv10.svg", "images/questions/solution_lv10.svg"),
  GameQuestion("images/questions/lv11.svg", "4180",
      "images/questions/hint_lv11.svg", "images/questions/solution_lv11.svg"),
  GameQuestion("images/questions/lv12.svg", "27",
      "images/questions/hint_lv12.svg", "images/questions/solution_lv12.svg"),
  GameQuestion("images/questions/lv13.svg", "28",
      "images/questions/hint_lv13.svg", "images/questions/solution_lv13.svg"),
  GameQuestion("images/questions/lv14.png", "13",
      "images/questions/hint_lv14.png", "images/questions/solution_lv14.png"),
  GameQuestion("images/questions/lv15.svg", "1",
      "images/questions/hint_lv15.svg", "images/questions/solution_lv15.svg"),
  GameQuestion("images/questions/lv16.svg", "90",
      "images/questions/hint_lv16.svg", "images/questions/solution_lv16.svg"),
  GameQuestion("images/questions/lv17.svg", "3",
      "images/questions/hint_lv17.svg", "images/questions/solution_lv17.svg"),
  GameQuestion("images/questions/lv18.svg", "63",
      "images/questions/hint_lv18.svg", "images/questions/solution_lv18.svg"),
  GameQuestion("images/questions/lv19.svg", "31",
      "images/questions/hint_lv19.svg", "images/questions/solution_lv19.svg"),
  GameQuestion("images/questions/lv20.svg", "4",
      "images/questions/hint_lv20.svg", "images/questions/solution_lv20.svg"),
  GameQuestion("images/questions/lv21.svg", "9561",
      "images/questions/hint_lv21.svg", "images/questions/solution_lv21.svg"),
  GameQuestion("images/questions/lv22.svg", "41",
      "images/questions/hint_lv22.svg", "images/questions/solution_lv22.svg"),
  GameQuestion("images/questions/lv23.svg", "25",
      "images/questions/hint_lv23.svg", "images/questions/solution_lv23.svg"),
  GameQuestion("images/questions/lv24.svg", "15",
      "images/questions/hint_lv24.svg", "images/questions/solution_lv24.svg"),
  GameQuestion("images/questions/lv25.svg", "7",
      "images/questions/hint_lv25.svg", "images/questions/solution_lv25.svg"),
  GameQuestion("images/questions/lv26.svg", "17",
      "images/questions/hint_lv26.svg", "images/questions/solution_lv26.svg"),
  GameQuestion("images/questions/lv27.svg", "16",
      "images/questions/hint_lv27.svg", "images/questions/solution_lv27.svg"),
  GameQuestion("images/questions/lv28.svg", "49",
      "images/questions/hint_lv28.svg", "images/questions/solution_lv28.svg"),
  GameQuestion("images/questions/lv29.svg", "64",
      "images/questions/hint_lv29.svg", "images/questions/solution_lv29.svg"),
  GameQuestion("images/questions/lv30.svg", "61",
      "images/questions/hint_lv30.svg", "images/questions/solution_lv30.svg"),
];
